### ISSUE TITLE
Efficient way of querying Twitch API

### ISSUE THREAD

**Issue by Loofn** [newbNox/rainbowcreators#19]
I realized that the old way of querying Twitch API did not actually take into account of the **tag** that was necessary, as we want to display streams with LGBTQIA tags. Old one did not do it as Twitch API does not support "tag" in their URL parameter.

I tried to fight this with just querying API multiple times in row, but I feel like it is not doing if efficiently, and not actually finding any streams with the tags...

[Referencing to this commit](https://github.com/newbNox/rainbowcreators/commit/b319c72b133abe38e9ed1e9902b516842533adc2)

**Comment by newbNox** [comment]
Asked this in [StackOverflow ](https://stackoverflow.com/questions/76846434/twitchapi-get-streams-and-filter-them-by-specific-stream-tag) too to find good answer for this.

**Comment by korhox** [comment]
You could try to search for channels with `live_only=true` and `query=lgbt`
https://dev.twitch.tv/docs/api/reference/#search-channels

**Comment by newbNox** [comment]
[Fixed](https://github.com/newbNox/rainbowcreators/commit/33b00b461600e9b5c4f19eb310bad41f0c00028a)
